# Generated by Django 6.1 on 2026-09-04 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Penguin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('species', models.CharField(max_length=50)),
                ('island', models.CharField(max_length=50)),
                ('bill_length_mm', models.FloatField()),
                ('bill_depth_mm', models.FloatField()),
                ('flipper_length_mm', models.PositiveIntegerField()),
                ('body_mass_g', models.PositiveIntegerField()),
                ('sex', models.CharField(blank=True, max_length=10)),
            ],
        ),
    ]
